# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
      - release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    # Condition to deploy the main branch only
    if: github.ref == 'refs/heads/main'

    # Steps to perform in a job
    steps:
      # Checkout code from repo
      - name: Checkout
        # package that runs checkout command
        uses: actions/checkout@v4

      # Install Node
      - name: Set up Node
        # package that runs npm install command
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build project
      - name: Build
        run: npm run build
        # Project's environment variables which are stored in github secret
        env:
          VITE_API_KEY: ${{secrets.VITE_API_KEY}}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload production-ready build files ( artifacts )
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'

  # 2nd job deploy
  deploy:
    # Name of the job
    name: deploy
    # To run this job build job needs to be completed
    needs: build
    # Server to run a job
    runs-on: ubuntu-latest
    # Condition to deploy the main branch only
    if: github.ref == 'refs/heads/main'

    # Steps to perform in a job
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
